### ISSUE TITLE
AttributeError: 'gi.repository.Gdk' object has no attribute 'window_process_all_updates'

### ISSUE THREAD

**Issue by atpage** [atpage/chirp#2]
```
ERROR: FIXMEPY3: 'gi.repository.Gdk' object has no attribute 'window_process_all_updates'
Traceback (most recent call last):
  File "/tmp/chirp/chirp/ui/compat.py", line 21, in py3safe
    yield
  File "/tmp/chirp/chirp/ui/mainapp.py", line 1033, in do_repeaterbook_political
    gtk.gdk.window_process_all_updates()
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 131, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gdk' object has no attribute 'window_process_all_updates'

```

**Comment by atpage** [comment]
198effdb8b649c00e4b20c4260c6d71f5aeafcd5
